### ISSUE TITLE
Javac Lint not working on Mac

### ISSUE THREAD

**Issue by hsoj95** [AtomLinter/linter-javac#107]
I have been trying to get linter-javac working in Atom for a bit now and can't seem to be able to do so. I have javac installed correctly, I can access it from the command line. I can also confirm that javac -Xlint also works from the command line. Other Linters, namely Lua Linter, works fine in Atom as well.

I have tried messing around with the path settings to no avail. 

Here is the error message I have gotten since I first started trying to get linter working:

```
Error: ENOENT: no such file or directory, lstat '/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:228:16)
    at Object.realpathSync (fs.js:1528:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:303:29)
    at /Users/Josh-iMac/.atom/packages/linter-javac/lib/init.coffee:252:23
    at Array.find (native)
    at Object.module.exports.getProjectRootDir (/Users/Josh-iMac/.atom/packages/linter-javac/lib/init.coffee:251:8)
    at Object.lint (/Users/Josh-iMac/.atom/packages/linter-javac/lib/init.coffee:93:20)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/Josh-iMac/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/Josh-iMac/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/Josh-iMac/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/Josh-iMac/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/Josh-iMac/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:755:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:734:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:695:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

I cleared all of the custom paths and setting before I took that error log, although changing the path settings seemed to make little difference. I tried doing a verbose logging of the error, but it never showed up in the developer console for Atom.

Maybe it's something stupid I'm doing! It'd really be helpful for me to get it working in Atom though! 

I'm running Mac OS X 10.11.6, in case that helps!

**Comment by florianb** [comment]
Hi @hsoj95, thanks for getting in touch and sorry for the late response. This is usually a bug popping up when moving Atom while it is running (usually by dragging it from Downloads to Applications).

I don't recognize this issue as being linter-javac-specific. So i will close this issue for now. Please feel free to come back if you'd like to add something.
