### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by guchenghao** [AtomLinter/linter-javac#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [linter-javac](https://github.com/AtomLinter/linter-javac) package, v1.2.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /opt/atom/resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/opt/atom/resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/opt/atom/resources/app.asar/src/buffered-process.js:52:14)
  at /home/dell/.atom/packages/linter-javac/node_modules/atom-linter/lib/helpers.coffee:45:30
  at Object.module.exports.Helpers._exec (/home/dell/.atom/packages/linter-javac/node_modules/atom-linter/lib/helpers.coffee:25:16)
  at Object.module.exports.Helpers.exec (/home/dell/.atom/packages/linter-javac/node_modules/atom-linter/lib/helpers.coffee:16:13)
  at Object.lint (/home/dell/.atom/packages/linter-javac/lib/init.coffee:62:15)
  at Promise.then._this.emitter.emit.linter (/home/dell/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/home/dell/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /home/dell/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /home/dell/.atom/packages/linter/lib/linter-registry.coffee:50:27

```

### Commands

```
     -6:21.6.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -6:21.5.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
 11x -6:17 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:58 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -5:58 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
  5x -5:45.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:39.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -5:12.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -5:08.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:08.0 script:run (atom-text-editor.editor.vim-mode.insert-mode)
     -4:42.6.0 emmet:balance-outward (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:36.7.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-material-ui)
     -4:34.8.0 emmet:balance-outward (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:31.2.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -4:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:55.6.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  },
  "linter-javac": {
    "javaExecutablePath": "/home/dell/program/java"
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.1
atom-beautify, v0.28.11
atom-material-ui, v0.6.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.9
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
jsformat, v0.9.0
language-ejs, v0.2.0
language-jade, v0.6.2
linter, v1.5.1
linter-cpplint, v0.1.4
linter-javac, v1.2.0
linter-jshint, v1.2.0
minimap, v4.13.3
minimap-linter, v1.0.0
monokai, v0.18.0
node-debugger, v1.1.8
script, v2.26.4
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Either `/home/dell/program/java` is a folder or it doesn't have execute permissions.
You should point `javaExecutablePath` at the java executable file.
