### ISSUE TITLE
Uncaught Error: Cannot find module 'shell-path'

### ISSUE THREAD

**Issue by BCasaleiro** [AtomLinter/linter-javac#85]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-javac](https://github.com/AtomLinter/linter-javac) package, v1.8.0

### Stack Trace

Uncaught Error: Cannot find module 'shell-path'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: Cannot find module 'shell-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at findOutPath (/Users/bcasaleiro/.atom/packages/linter-javac/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:24:21)
    at getPath (/Users/bcasaleiro/.atom/packages/linter-javac/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:17:16)
    at Object.exec (/Users/bcasaleiro/.atom/packages/linter-javac/node_modules/atom-linter/lib/helpers.js:116:59)
    at Object.exec (/Users/bcasaleiro/.atom/packages/linter-javac/node_modules/atom-linter/lib/index.js:158:18)
    at Object.lint (/Users/bcasaleiro/.atom/packages/linter-gcc/lib/main.js:75:20)
    at lintOnSave (/Users/bcasaleiro/.atom/packages/linter-gcc/lib/main.js:132:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -8:39.3.0 core:paste (atom-text-editor.editor.is-focused)
     -8:39 core:save (atom-text-editor.editor.is-focused)
     -8:34.8.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -8:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -8:04.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:43.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.theme-one-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
     -6:45.1.0 core:save (atom-text-editor.editor.is-focused)
     -6:36.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:35.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:34 settings-view:open (atom-text-editor.editor.is-focused)
     -6:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:02.0 core:save (atom-text-editor.editor.is-focused)
  4x -5:55.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-clang"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0
angularjs, v0.3.4
atom-typescript, v8.3.0
language-latex, v0.6.1
language-lex-flex, v0.1.0
language-nginx, v0.6.1
linter, v1.11.3
linter-gcc, v0.6.8
linter-javac, v1.8.0
meteor-api, v2.20.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Can you uninstall and re-install `linter-javac`? It looks like Atom failed to install all the dependencies... but the current version of the `atom-linter` dependency doesn't even _have_ a dependency on `shell-path`, so that is out of date anyway :stuck_out_tongue:

**Comment by florianb** [comment]
I'm sorry @Arcanemagus - that's not right. :-1: 

@BCasaleiro - thank you for filing that issue! :candy:

The `shell-path`-module is a inherited dependency of `atom-linter`@`4.5.0`. The responsible module was removed with version 4.6.0 of `atom-linter`. I will therefore create a patch of `linter-javac` which efforts a newer version of `atom-linter`.

**Comment by florianb** [comment]
@BCasaleiro - i published a patch recently. I'd like to ask you to install that update and afterwards leave a message here if the issue is resolved. Thank you very much.

**Comment by Arcanemagus** [comment]
@florianb Well, it was only half wrong, the latest version of `atom-linter` follows exactly what I said, and re-installing `linter-javac` would (should...) have installed it, the _minimum_ version though does still have it as a dependency, so good call on updating there.

**Comment by florianb** [comment]
@Arcanemagus that wasn't meant offensive. But before i ask the user to do anything (which is bad enough as long as my objective is delivering faultless software) i prefer figuring out if i can something to avoid any user intervention.

And i experienced that most of the people just drop the :bomb: and don't show up again. So i try to lower the barrier for people to finally confirm the patch or the bug.

**Comment by BCasaleiro** [comment]
@florianb it seems to be working just fine. Thank you
